# DAT405 Assignment 5 - Reinforcement learning and classification
## Group 2

### Francisco Boudagh
### Jakob Engström

### May 12, 2023


------------------

# Problem 1
## 1. a) Optimal path

The optimal path is the one with the highest reward.

|    |    |    |
|----------|----------|----------|
|   -1     |    1     |    F     |
|    0     |   -1     |    1     |
|   -1     |    0     |   -1     |
|    S     |   -1     |    1     |



To move from $S$ to $F$ we can go $EENNN$ or $EENNWNE$ and both gives a reward $0$, which is the highest score one can get. So the path is not unique since there are two. The first path, $EENNN$ is shorter; 5 steps when the second path, $EENNWNE$ is longer; 7 steps.

## 1. b) Optimal policy

Every state could be described by $x$ and $y$ coordinates in the grid. Optimal policy could be obtained by choosing the direction which gives the most reward

$[[E, E, -]$

$[NSE, NE, N]$

$[NE, NSEW, NS]$

$[NE, E, NW]]$

## 1. c) Reward in a)

The reward in a) is zero: $-1+1-1+1=0$

------------------

# Problem 2
## 2. a) Iteration algorithm using Bellman equation

In [13]:
import numpy as np

def value(states, reward, gamma, epsilon, p):
    next_state = np.zeros_like(states)
    policy = np.empty(states.shape, dtype=object)

    def move(i, j):
        m, n = states.shape
        for x, y, action in [(i-1, j, 'N'), (i, j+1, 'E'), (i+1, j, 'S'), (i, j-1, 'W')]:
            if 0 <= x < m and 0 <= y < n:
                yield x, y, action

    def rewards(c_current, c_next):
        action_reward = p * (reward[c_next] + gamma * next_state[c_next]) + (1-p) * (reward[c_current] + gamma * next_state[c_current])
        return action_reward

    differ = float('inf')
    while differ > epsilon:
        differ = 0
        for i in range(states.shape[0]):
            for j in range(states.shape[1]):
                actions = list(move(i, j))
                max_reward = float('-inf')
                best_actions = []
                for action in actions:
                    action_reward = rewards((i, j), action[:2])
                    if action_reward > max_reward:
                        max_reward = action_reward
                        best_actions = [action[2]]
                    elif action_reward == max_reward:
                        best_actions.append(action[2])
                next_state[i][j] = max_reward
                policy[i][j] = best_actions
                differ = max(differ, abs(states[i][j] - next_state[i][j]))
        np.copyto(states, next_state)

    print(states)
    for row in policy:
        print(', '.join([''.join(actions) for actions in row]))


# testing with given example
reward = np.array([[0, 0, 0], [0, 10, 0], [0, 0, 0]], dtype=float)
states = np.zeros_like(reward)
epsilon = 1e-10
gamma = 0.9
p = 0.8
value(states, reward, gamma, epsilon, p)


[[45.61292366 51.94805195 45.61292366]
 [51.94805195 48.05194805 51.94805195]
 [45.61292366 51.94805195 45.61292366]]
ES, S, SW
E, NESW, W
NE, N, NW


## 2. b) Independence of the initial value $V_0$

Because whatever the initial value $V_0$ is, the algorithm (using Bellman equation) will iterively update itself until convergence. And by using the Bellman equation we are converging towards the maximum value. So, analogically, if we have a continuos graphical function, it does not matter where we start on the function if we are aiming toward the maximum value, the starting point will only affect the time for us to get to the maximum.

## 2. c) Discount factor $\gamma$

The discount factor $\gamma$ is a value between $0$ and $1$. It is a factor for how much future rewards are valued. A $\gamma$ value of $1$ means that the agent is both long term and short term sighted, meaning future rewards are as important as the near-future rewards. When $\gamma$ is $0$, it means that the agent is short-sighted and will only take an action based on the present rewards.

The gamma factor depends on the specific case. For example, an agent that is navigating through a maze shoud definetily have a high $\gamma$ value to be able to consider future rewards and find the optimal path through the maze. If $\gamma$ was set to to a small value in maze-case, this could result in a big problem since the agent could easily be stuck in dead end loops and never find a way out of the maze.

------------------

# ...


------------------

# Problem 4
## 4. a) Importance of exploaration in Reinforcement Learning

Exploration in reinforcemnt learning could be seen as trial and error. If no exploration is done, better paths or ways that make the process more effective can not be utilized. An example could be a game of chess. If new to the game, one makes simple moves which probably will lead to a lot of beginners mistakes. If you decide not to play regularly you will make the same mistakes the next time you play. But if you decide to play often (explore) you will learn what moves work the best and as you play different opponents you will gradually be able to use different tactics on different kind of opponents, slowly becoming a master of chess due to exploration, trial and error.

## 4. b) Reinforcement Learning vs Supervised Learning

In supervised learning such as Classification and Regression one has a set of data of which the program learns from and then given a new data set either classifies it based on given data or if given a parameter predicts the associated value from the function from regression. So the goal is to place a given data point in a matching context. In Reinforecment learnin however the agent "learns" by trying diferent paths and actions.

So the main difference is that in RL the agent explores the environment and learns by the consequenses of actions while in SL the agent is given a dataset for learning. 

------------------

# Problem 5
## 5. a) Decision trees extension to random forests

A decision tree is a set of instructions that helps us make decisions step by step. However a problem with decision trees is that they can become too focused on the specific data they were trained on, which is called overfitting. This means that if we use the same decision tree on a different dataset, it may not work well.

To overcome this issue, we can use something called a random forest. In a random foeest, we create multiple decision trees, but each tree only looks at a random part of the dataset. By doing this, the trees are trained a bit differently from each other.

The final result of a random forest is obtained by combining the predictions of all the individual trees. This will help to reduce the overfitting problem and provides a more accurate outcome compared to using just one decision tree.

## 5. b) Random forests vs decision trees

The random forest main advantage is the reduced risk of overfitting, however it is a bit harder to interpret and takes more computational power to construct since there are several trees to be made.